<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JaskInterpreter</RootNamespace>
    <PublishAot>true</PublishAot>
    <AssemblyName>jask</AssemblyName>
  </PropertyGroup>

  <Target Name="SetBuildDate" BeforeTargets="GetAssemblyAttributes">
    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
        <_Parameter1>BuildDate</_Parameter1>
        <_Parameter2>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss")) UTC</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>

  <Target Name="SetGitCommitHash" BeforeTargets="BeforeCompile">
    <Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" StandardOutputImportance="low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitCommitHash" />
    </Exec>
    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
        <_Parameter1>GitCommitHash</_Parameter1>
        <_Parameter2>$(GitCommitHash)</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="$(MSBuildThisFileDirectory)../jcore/*.jask" />
  </ItemGroup>

</Project>
